name: 'Build get-keyvault-secret action'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:

      - run: npm i -g @vercel/ncc

      - run: ncc build lib/main.js