name: 'Test get-keyvault-secret action'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      
  workflow_dispatch:
    
jobs:
  test: 
    name: 'Test action'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: 'Build action code'
        run: npm install

      - name: 'Login into Azure'
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZUREAD_CLIENT_ID }}","clientSecret":"${{ secrets.AZUREAD_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZUREAD_TENANT_ID }}"}'

      - uses: ./
        name: 'Retrieve a secret from KeyVault'
        with:
          keyvault: GetKeyVaultSecretAction
          secrets: 'SampleSecret'